### ISSUE TITLE
Can this be used for interactive login?

### ISSUE THREAD

**Issue by dkattan** [eladshamir/Whisker#5]
This might sound like a dumb question but hear me out. IT guys spend a lot of time troubleshooting things on behalf of end users. Recently Microsoft announced [Temporary Access Passwords](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/temporary-access-pass-is-now-in-public-preview/ba-p/1994702) that allow technicians to login as users for a predetermined amount of time to configure things that can only be configured easily in user space.

So lets say you re setting up a computer for an end user. In order for this to work you'd have to enable the web sign-in auth package in Windows, which is only available on AzureAD joined machines and doens't work in domain-joined/hybrid joined environments. I'm looking for something that works in traditional domain/hybrid environments.

It appears to me that the technique in Whisker could be used to legitimately add shadow PINs for Windows Hello for Business, and potentially time limit them via certificate expiration. In this scenario, we have a Windows Service running on both the domain controller and the target machine that allows for arbitrary code execution, meaning if WHfB isn't enabled on the device, I can likely register it.

I suppose the only trick here would be knowing the device id of the machine so that Whisker can add the credential to the appropriate device, allowing for interactive logon for the target user.

Am I on the right track?

**Comment by eladshamir** [comment]
That's a very interesting idea for further research. I don't know the answer off the top of my head, but I'd love to look into it when I get the chance.
